#!/usr/bin/env bash

rm -rf wasm
mkdir wasm

npx jco componentize dist/out.js --wit src/nana.wit -o wasm/nana.wasm

npx jco transpile wasm/nana.wasm -o wasm/transpiled

cp src/wasmtest.js wasm/
node wasm/wasmtest.js